name: Python package

on: [push]
  
jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.7"]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest
          pip install pandas
          pip install numpy
          pip install pylint
          pip install black
          # pip3 install torch torchvision torchaudio -f https://download.pytorch.org/whl/cpu/torch_stable.html
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Lint with flake8
        run: |
          # stop the build if there are Python syntax errors or undefined names
          # flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
          # flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
      - name: Test with pytest
        run: |
          pytest ML_tests/LinearRegression_tests/LinearRegression_GD.py
          pytest ML_tests/LinearRegression_tests/LinearRegression_normal.py
          pytest tree/unit-test-branch/ML_tests/NaiveBayes_tests
          pytest tree/unit-test-branch/ML_tests//ML_tests/KMeans_tests/KMeans.py
